services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: lunch
      POSTGRES_PASSWORD: lunch
      POSTGRES_DB: lunch_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
